### ISSUE TITLE
Work on!

### ISSUE THREAD

**Issue by leomaurodesenv** [aboood40091/PointlessMaker#1]
Hello,

I trying to develop a similar project.   
Open SMM courses and display in a web browser called [smm-course-viewer](https://github.com/leomaurodesenv/smm-course-viewer).   
   
_I want to know where you find this organized titleset of Super Mario Maker._

**Comment by leomaurodesenv** [comment]
I know it is possible to open `.szs > .gtx > .bfres > .dds > .png`.
I try, but some figures had a problem with colors, mainly the WU figures.
Addition, thanks for your vast work to Wii U community. I saw many works, like this, [SARCExtract](https://github.com/aboood40091/SARCExtract) and other.

**Comment by aboood40091** [comment]
SARCExtract is very old. I recommend you to look at [libyaz0](https://github.com/aboood40091/libyaz0) and [SarcLib](https://github.com/aboood40091/SarcLib) instead.
For getting textures, take a look at [BFRES Tool](https://github.com/aboood40091/BFRES-Tool).
(Specifically, [this](https://github.com/aboood40091/BFRES-Tool/blob/master/bfres.py#L35) for loading all textures, [this](https://github.com/aboood40091/BFRES-Tool/blob/master/bfres.py#L165) for untiling a texture and from [here](https://github.com/aboood40091/BFRES-Tool/blob/master/main.py#L469) to [here](https://github.com/aboood40091/BFRES-Tool/blob/master/main.py#L556) for converting all supported texture formats to RGBA8 (to save as PNG))

**Comment by leomaurodesenv** [comment]
@aboood40091 , Thanks a lot!
Really, you helped me. 

For now, one more thing:
I found the field folder: `000500001018DC00/content/Model`, also personas.
Do you know which folder has the monsters texture?

I will continue in this work... Anything else, can I contact you for this _issue_?

**Comment by leomaurodesenv** [comment]
Hello @aboood40091, 

Thanks for everything.
I found an amazing tutorial [GRAnimated/SMMGuide](https://github.com/GRAnimated/SMMGuide/wiki), some codes outdated, but the explanations and tutorial help a lot.

Thanks again.
