### ISSUE TITLE
Not all tiles render as an image

### ISSUE THREAD

**Issue by johndpope** [aboood40091/PointlessMaker#3]
https://github.com/aboood40091/PointlessMaker/blob/a4dd94eed650b0d614c98ae59a95146a9c3956ab/Images/LevelShot.png

this level has some numbers that I guess the texture maps don't match?
is there some steps that you could spell out to fix this? some sort of automated way to build this?

I'm aware of this tool - 
https://github.com/johndpope/BFRES-Tool

Did you consider using proto buffers at anytime to streamline python parsing code?
eg.
https://github.com/Tarnadas/smm-protobuf/blob/master/proto/Tile.proto

**Comment by aboood40091** [comment]
I am not sure if I'll ever work on this editor again, but this is on my todo list _in case I decide to work on the editor again._
